stages:
  - test

tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.22.0-focal
  script:
    - npm install
    - npx playwright install
    - npm run allure:clean
    - npm run test:firefox
  artifacts:
     when: always
     paths:
          - allure-report/
          - allure-results/


