stages:
  - testing
  - deploy 

docker_job:
  stage: testing
  tags:
    - docker
 image: mcr.microsoft.com/playwright:v1.34.3-jammy

  before_script:
    - npm ci
    - npx playwright install-deps   
    - npx playwright install
    - npm run allure:clean
    - npm install allure-playwright --save-dev
  script:
    - npm run test:firefox
    
  after_script:
    - npx allure generate allure-results --clean 
  rules:
      - when: always
  allow_failure: false
  artifacts: 
    when: always
    paths:
      - ./allure-report
    expire_in: 1 day 

pages: 
  stage: deploy
  script:
    - mkdir public 
    - mv ./allure-report/* public
  artifacts:
    paths:
      - public
  rules:
    - when: always


