stages:
  - testing
  - deploy 

docker_job:
  stage: testing
  tags:
    - docker
  image: atools/chrome-headless:java11-node14-latest 

  before_script:
    - npm install
    - npx playwright install
    - npm install allure-commandline --save-dev
  script:
    - npm run test:firefox
    
  after_script:
    - npx allure generate allure-results
  rules:
      - when: always
  allow_failure: true
  artifacts: 
    when: always
    paths:
      - ./allure-report
    expire_in: 1 day 

pages: 
  stage: deploy
  script:
    - mkdir public 
    - mv ./allure-report/* public
  artifacts:
    paths:
      - public
  rules:
    - when: always


